// Centralized city data for consistent use across the application
export const cities = [
  // Major Metro Cities
  { value: 'mumbai', label: 'Mumbai' },
  { value: 'delhi', label: 'Delhi' },
  { value: 'bangalore', label: 'Bangalore' },
  { value: 'hyderabad', label: 'Hyderabad' },
  { value: 'chennai', label: 'Chennai' },
  { value: 'kolkata', label: 'Kolkata' },
  { value: 'pune', label: 'Pune' },
  
  // Gujarat Cities
  { value: 'ahmedabad', label: 'Ahmedabad' },
  { value: 'surat', label: 'Surat' },
  { value: 'vadodara', label: 'Vadodara' },
  { value: 'rajkot', label: 'Rajkot' },
  { value: 'bhavnagar', label: 'Bhavnagar' },
  { value: 'jamnagar', label: 'Jamnagar' },
  { value: 'gandhinagar', label: 'Gandhinagar' },
  { value: 'anand', label: 'Anand' },
  { value: 'bharuch', label: 'Bharuch' },
  { value: 'vapi', label: 'Vapi' },
  { value: 'navsari', label: 'Navsari' },
  { value: 'morbi', label: 'Morbi' },
  { value: 'nadiad', label: 'Nadiad' },
  { value: 'surendranagar', label: 'Surendranagar' },
  { value: 'gandhidham', label: 'Gandhidham' },
  { value: 'junagadh', label: 'Junagadh' },
  { value: 'veraval', label: 'Veraval' },
  { value: 'porbandar', label: 'Porbandar' },
  { value: 'godhra', label: 'Godhra' },
  { value: 'botad', label: 'Botad' },
  { value: 'palanpur', label: 'Palanpur' },
  { value: 'valsad', label: 'Valsad' },
  { value: 'mehsana', label: 'Mehsana' },
  { value: 'patan', label: 'Patan' },
  { value: 'amreli', label: 'Amreli' },
  { value: 'dwarka', label: 'Dwarka' },
  { value: 'bhuj', label: 'Bhuj' },
  { value: 'dahod', label: 'Dahod' },
  { value: 'kalol', label: 'Kalol' },
  { value: 'himmatnagar', label: 'Himmatnagar' },
  { value: 'idar', label: 'Idar' },
  { value: 'jetpur', label: 'Jetpur' },
  { value: 'khambhat', label: 'Khambhat' },
  { value: 'mahuva', label: 'Mahuva' },
  { value: 'modasa', label: 'Modasa' },
  { value: 'palitana', label: 'Palitana' },
  { value: 'petlad', label: 'Petlad' },
  { value: 'radhanpur', label: 'Radhanpur' },
  { value: 'rajpipla', label: 'Rajpipla' },
  { value: 'sidhpur', label: 'Sidhpur' },
  { value: 'tapi', label: 'Tapi' },
  { value: 'unjha', label: 'Unjha' },
  { value: 'upleta', label: 'Upleta' },
  { value: 'vyara', label: 'Vyara' },
  { value: 'wankaner', label: 'Wankaner' },
  
  // Rajasthan Cities
  { value: 'jaipur', label: 'Jaipur' },
  { value: 'jodhpur', label: 'Jodhpur' },
  { value: 'kota', label: 'Kota' },
  { value: 'bikaner', label: 'Bikaner' },
  { value: 'ajmer', label: 'Ajmer' },
  { value: 'udaipur', label: 'Udaipur' },
  { value: 'alwar', label: 'Alwar' },
  { value: 'bharatpur', label: 'Bharatpur' },
  { value: 'sikar', label: 'Sikar' },
  { value: 'pali', label: 'Pali' },
  { value: 'tonk', label: 'Tonk' },
  { value: 'kishangarh', label: 'Kishangarh' },
  { value: 'beawar', label: 'Beawar' },
  { value: 'hanumangarh', label: 'Hanumangarh' },
  { value: 'gangapur', label: 'Gangapur City' },
  { value: 'churu', label: 'Churu' },
  { value: 'jhunjhunu', label: 'Jhunjhunu' },
  { value: 'sri-ganganagar', label: 'Sri Ganganagar' },
  { value: 'sawai-madhopur', label: 'Sawai Madhopur' },
  { value: 'makrana', label: 'Makrana' },
  { value: 'sujangarh', label: 'Sujangarh' },
  { value: 'lachhmangarh', label: 'Lachhmangarh' },
  { value: 'nokha', label: 'Nokha' },
  { value: 'nimbahera', label: 'Nimbahera' },
  { value: 'suratgarh', label: 'Suratgarh' },
  { value: 'rajsamand', label: 'Rajsamand' },
  { value: 'fatehpur-shekhawati', label: 'Fatehpur Shekhawati' },
  { value: 'ratangarh', label: 'Ratangarh' },
  { value: 'rawatbhata', label: 'Rawatbhata' },
  { value: 'rajgarh-churu', label: 'Rajgarh (Churu)' },
  { value: 'sadri', label: 'Sadri' },
  { value: 'taranagar', label: 'Taranagar' },
  { value: 'todabhim', label: 'Todabhim' },
  { value: 'kuchaman-city', label: 'Kuchaman City' },
  { value: 'didwana', label: 'Didwana' },
  { value: 'kishanganj', label: 'Kishanganj' },
  { value: 'dausa', label: 'Dausa' },
  { value: 'chittorgarh', label: 'Chittorgarh' },
  { value: 'pratapgarh', label: 'Pratapgarh' },
  { value: 'mount-abu', label: 'Mount Abu' },
  { value: 'nathdwara', label: 'Nathdwara' },
  
  // Uttar Pradesh Cities
  { value: 'lucknow', label: 'Lucknow' },
  { value: 'kanpur', label: 'Kanpur' },
  { value: 'ghaziabad', label: 'Ghaziabad' },
  { value: 'agra', label: 'Agra' },
  { value: 'faridabad', label: 'Faridabad' },
  { value: 'meerut', label: 'Meerut' },
  { value: 'varanasi', label: 'Varanasi' },
  { value: 'allahabad', label: 'Allahabad' },
  { value: 'bareilly', label: 'Bareilly' },
  { value: 'aligarh', label: 'Aligarh' },
  { value: 'saharanpur', label: 'Saharanpur' },
  { value: 'firozabad', label: 'Firozabad' },
  { value: 'loni', label: 'Loni' },
  { value: 'jhansi', label: 'Jhansi' },
  { value: 'noida', label: 'Noida' },
  { value: 'gurgaon', label: 'Gurgaon' },
  { value: 'mathura', label: 'Mathura' },
  { value: 'muzaffarnagar', label: 'Muzaffarnagar' },
  { value: 'rampur', label: 'Rampur' },
  { value: 'shahjahanpur', label: 'Shahjahanpur' },
  { value: 'farrukhabad', label: 'Farrukhabad' },
  { value: 'hapur', label: 'Hapur' },
  { value: 'etawah', label: 'Etawah' },
  { value: 'mirzapur', label: 'Mirzapur' },
  { value: 'bulandshahr', label: 'Bulandshahr' },
  { value: 'sambhal', label: 'Sambhal' },
  { value: 'amroha', label: 'Amroha' },
  { value: 'hardoi', label: 'Hardoi' },
  { value: 'fatehpur', label: 'Fatehpur' },
  { value: 'raebareli', label: 'Raebareli' },
  { value: 'orai', label: 'Orai' },
  { value: 'sitapur', label: 'Sitapur' },
  { value: 'bahraich', label: 'Bahraich' },
  { value: 'modinagar', label: 'Modinagar' },
  { value: 'unnao', label: 'Unnao' },
  { value: 'jaunpur', label: 'Jaunpur' },
  { value: 'lakhimpur', label: 'Lakhimpur' },
  { value: 'hathras', label: 'Hathras' },
  { value: 'banda', label: 'Banda' },
  { value: 'pilibhit', label: 'Pilibhit' },
  { value: 'barabanki', label: 'Barabanki' },
  { value: 'khurja', label: 'Khurja' },
  { value: 'gonda', label: 'Gonda' },
  { value: 'mainpuri', label: 'Mainpuri' },
  { value: 'lalitpur', label: 'Lalitpur' },
  { value: 'etah', label: 'Etah' },
  { value: 'deoria', label: 'Deoria' },
  { value: 'ujhani', label: 'Ujhani' },
  { value: 'ghazipur', label: 'Ghazipur' },
  { value: 'sultanpur', label: 'Sultanpur' },
  { value: 'azamgarh', label: 'Azamgarh' },
  { value: 'bijnor', label: 'Bijnor' },
  { value: 'sahaswan', label: 'Sahaswan' },
  { value: 'basti', label: 'Basti' },
  { value: 'chandausi', label: 'Chandausi' },
  { value: 'akbarpur', label: 'Akbarpur' },
  { value: 'ballia', label: 'Ballia' },
  { value: 'tanda', label: 'Tanda' },
  { value: 'greater-noida', label: 'Greater Noida' },
  { value: 'shikohabad', label: 'Shikohabad' },
  { value: 'shamli', label: 'Shamli' },
  { value: 'awagarh', label: 'Awagarh' },
  { value: 'kasganj', label: 'Kasganj' },
  
  // Maharashtra Cities
  { value: 'thane', label: 'Thane' },
  { value: 'nashik', label: 'Nashik' },
  { value: 'kalyan', label: 'Kalyan-Dombivali' },
  { value: 'vasai', label: 'Vasai-Virar' },
  { value: 'aurangabad', label: 'Aurangabad' },
  { value: 'navi-mumbai', label: 'Navi Mumbai' },
  { value: 'solapur', label: 'Solapur' },
  { value: 'mira', label: 'Mira-Bhayandar' },
  { value: 'bhiwandi', label: 'Bhiwandi' },
  { value: 'amravati', label: 'Amravati' },
  { value: 'nanded', label: 'Nanded' },
  { value: 'kolhapur', label: 'Kolhapur' },
  { value: 'akola', label: 'Akola' },
  { value: 'ulhasnagar', label: 'Ulhasnagar' },
  { value: 'sangli', label: 'Sangli-Miraj & Kupwad' },
  { value: 'malegaon', label: 'Malegaon' },
  { value: 'jalgaon', label: 'Jalgaon' },
  { value: 'ahmednagar', label: 'Ahmednagar' },
  { value: 'dhule', label: 'Dhule' },
  { value: 'ichalkaranji', label: 'Ichalkaranji' },
  { value: 'chandrapur', label: 'Chandrapur' },
  { value: 'parbhani', label: 'Parbhani' },
  { value: 'jalna', label: 'Jalna' },
  { value: 'ambajogai', label: 'Ambajogai' },
  { value: 'shrirampur', label: 'Shrirampur' },
  { value: 'baramati', label: 'Baramati' },
  { value: 'osmanabad', label: 'Osmanabad' },
  { value: 'nandurbar', label: 'Nandurbar' },
  { value: 'satara', label: 'Satara' },
  { value: 'wardha', label: 'Wardha' },
  { value: 'udgir', label: 'Udgir' },
  { value: 'achalpur', label: 'Achalpur' },
  
  // West Bengal Cities
  { value: 'howrah', label: 'Howrah' },
  { value: 'durgapur', label: 'Durgapur' },
  { value: 'asansol', label: 'Asansol' },
  { value: 'siliguri', label: 'Siliguri' },
  { value: 'maheshtala', label: 'Maheshtala' },
  { value: 'rajpur-sonarpur', label: 'Rajpur Sonarpur' },
  { value: 'south-dumdum', label: 'South Dumdum' },
  { value: 'bhatpara', label: 'Bhatpara' },
  { value: 'panihati', label: 'Panihati' },
  { value: 'kamarhati', label: 'Kamarhati' },
  { value: 'madhyamgram', label: 'Madhyamgram' },
  { value: 'barasat', label: 'Barasat' },
  { value: 'raiganj', label: 'Raiganj' },
  { value: 'dum-dum', label: 'Dum Dum' },
  { value: 'rajarhat-gopalpur', label: 'Rajarhat Gopalpur' },
  { value: 'serampore', label: 'Serampore' },
  { value: 'kharagpur', label: 'Kharagpur' },
  { value: 'naihati', label: 'Naihati' },
  { value: 'english-bazar', label: 'English Bazar' },
  { value: 'baharampur', label: 'Baharampur' },
  { value: 'hugli-chinsurah', label: 'Hugli-Chinsurah' },
  { value: 'cooch-behar', label: 'Cooch Behar' },
  { value: 'kanchrapara', label: 'Kanchrapara' },
  { value: 'alipore', label: 'Alipore' },
  { value: 'balurghat', label: 'Balurghat' },
  { value: 'basirhat', label: 'Basirhat' },
  { value: 'bankura', label: 'Bankura' },
  { value: 'chakdaha', label: 'Chakdaha' },
  { value: 'darjeeling', label: 'Darjeeling' },
  { value: 'alipurduar', label: 'Alipurduar' },
  { value: 'purulia', label: 'Purulia' },
  { value: 'jangipur', label: 'Jangipur' },
  { value: 'bolpur', label: 'Bolpur' },
  { value: 'bangaon', label: 'Bangaon' },
  
  // Tamil Nadu Cities
  { value: 'coimbatore', label: 'Coimbatore' },
  { value: 'madurai', label: 'Madurai' },
  { value: 'tiruchirappalli', label: 'Tiruchirappalli' },
  { value: 'tiruppur', label: 'Tiruppur' },
  { value: 'salem', label: 'Salem' },
  { value: 'ambattur', label: 'Ambattur' },
  { value: 'tirunelveli', label: 'Tirunelveli' },
  { value: 'erode', label: 'Erode' },
  { value: 'vellore', label: 'Vellore' },
  { value: 'thoothukudi', label: 'Thoothukudi' },
  { value: 'dindigul', label: 'Dindigul' },
  { value: 'thanjavur', label: 'Thanjavur' },
  { value: 'ranipet', label: 'Ranipet' },
  { value: 'sivakasi', label: 'Sivakasi' },
  { value: 'karur', label: 'Karur' },
  { value: 'udhagamandalam', label: 'Udhagamandalam' },
  { value: 'hosur', label: 'Hosur' },
  { value: 'nagercoil', label: 'Nagercoil' },
  { value: 'kanchipuram', label: 'Kanchipuram' },
  { value: 'kumarakonam', label: 'Kumarakonam' },
  { value: 'pollachi', label: 'Pollachi' },
  { value: 'rajapalayam', label: 'Rajapalayam' },
  { value: 'pudukkottai', label: 'Pudukkottai' },
  
  // Karnataka Cities
  { value: 'hubli', label: 'Hubli-Dharwad' },
  { value: 'mysore', label: 'Mysore' },
  { value: 'mangalore', label: 'Mangalore' },
  { value: 'belgaum', label: 'Belgaum' },
  { value: 'gulbarga', label: 'Gulbarga' },
  { value: 'davanagere', label: 'Davanagere' },
  { value: 'bellary', label: 'Bellary' },
  { value: 'bijapur', label: 'Bijapur' },
  { value: 'shimoga', label: 'Shimoga' },
  { value: 'tumkur', label: 'Tumkur' },
  { value: 'raichur', label: 'Raichur' },
  { value: 'bidar', label: 'Bidar' },
  { value: 'hospet', label: 'Hospet' },
  { value: 'gadag-betigeri', label: 'Gadag-Betigeri' },
  { value: 'udupi', label: 'Udupi' },
  { value: 'robertson-pet', label: 'Robertson Pet' },
  { value: 'bhadravati', label: 'Bhadravati' },
  { value: 'chitradurga', label: 'Chitradurga' },
  { value: 'hassan', label: 'Hassan' },
  { value: 'mandya', label: 'Mandya' },
  { value: 'chikmagalur', label: 'Chikmagalur' },
  { value: 'bagalkot', label: 'Bagalkot' },
  { value: 'karwar', label: 'Karwar' },
  
  // Kerala Cities
  { value: 'thiruvananthapuram', label: 'Thiruvananthapuram' },
  { value: 'kochi', label: 'Kochi' },
  { value: 'kozhikode', label: 'Kozhikode' },
  { value: 'kollam', label: 'Kollam' },
  { value: 'thrissur', label: 'Thrissur' },
  { value: 'alappuzha', label: 'Alappuzha' },
  { value: 'palakkad', label: 'Palakkad' },
  { value: 'kannur', label: 'Kannur' },
  { value: 'payyanur', label: 'Payyanur' },
  { value: 'kanhangad', label: 'Kanhangad' },
  { value: 'koyilandy', label: 'Koyilandy' },
  { value: 'parappanangadi', label: 'Parappanangadi' },
  { value: 'kalamassery', label: 'Kalamassery' },
  { value: 'neyyattinkara', label: 'Neyyattinkara' },
  { value: 'kayamkulam', label: 'Kayamkulam' },
  { value: 'nedumangad', label: 'Nedumangad' },
  { value: 'tirur', label: 'Tirur' },
  { value: 'kottayam', label: 'Kottayam' },
  { value: 'kasaragod', label: 'Kasaragod' },
  { value: 'kunnamkulam', label: 'Kunnamkulam' },
  { value: 'ottappalam', label: 'Ottappalam' },
  { value: 'thiruvalla', label: 'Thiruvalla' },
  { value: 'thodupuzha', label: 'Thodupuzha' },
  { value: 'chalakudy', label: 'Chalakudy' },
  { value: 'changanassery', label: 'Changanassery' },
  { value: 'punalur', label: 'Punalur' },
  { value: 'nilambur', label: 'Nilambur' },
  { value: 'cherthala', label: 'Cherthala' },
  { value: 'perinthalmanna', label: 'Perinthalmanna' },
  { value: 'mattannur', label: 'Mattannur' },
  { value: 'mavelikkara', label: 'Mavelikkara' },
  
  // Andhra Pradesh & Telangana Cities
  { value: 'visakhapatnam', label: 'Visakhapatnam' },
  { value: 'vijayawada', label: 'Vijayawada' },
  { value: 'guntur', label: 'Guntur' },
  { value: 'nellore', label: 'Nellore' },
  { value: 'warangal', label: 'Warangal' },
  { value: 'tirupati', label: 'Tirupati' },
  { value: 'kakinada', label: 'Kakinada' },
  { value: 'rajahmundry', label: 'Rajahmundry' },
  { value: 'nizamabad', label: 'Nizamabad' },
  { value: 'eluru', label: 'Eluru' },
  { value: 'ongole', label: 'Ongole' },
  { value: 'nandyal', label: 'Nandyal' },
  { value: 'machilipatnam', label: 'Machilipatnam' },
  { value: 'adoni', label: 'Adoni' },
  { value: 'tenali', label: 'Tenali' },
  { value: 'proddatur', label: 'Proddatur' },
  { value: 'chittoor', label: 'Chittoor' },
  { value: 'hindupur', label: 'Hindupur' },
  { value: 'bhimavaram', label: 'Bhimavaram' },
  { value: 'madanapalle', label: 'Madanapalle' },
  { value: 'guntakal', label: 'Guntakal' },
  { value: 'dharmavaram', label: 'Dharmavaram' },
  { value: 'gudivada', label: 'Gudivada' },
  { value: 'narasaraopet', label: 'Narasaraopet' },
  { value: 'kadapa', label: 'Kadapa' },
  { value: 'tadipatri', label: 'Tadipatri' },
  { value: 'mangalagiri', label: 'Mangalagiri' },
  { value: 'chirala', label: 'Chirala' },
  { value: 'anakapalle', label: 'Anakapalle' },
  { value: 'kavali', label: 'Kavali' },
  { value: 'palacole', label: 'Palacole' },
  { value: 'sullurpeta', label: 'Sullurpeta' },
  { value: 'tanuku', label: 'Tanuku' },
  { value: 'rayachoti', label: 'Rayachoti' },
  { value: 'srikalahasti', label: 'Srikalahasti' },
  { value: 'bapatla', label: 'Bapatla' },
  { value: 'rajam', label: 'Rajam' },
  { value: 'bobbili', label: 'Bobbili' },
  { value: 'narasapuram', label: 'Narasapuram' },
  { value: 'tadepalligudem', label: 'Tadepalligudem' },
  { value: 'repalle', label: 'Repalle' },
  { value: 'vinukonda', label: 'Vinukonda' },
  { value: 'jaggaiahpet', label: 'Jaggaiahpet' },
  { value: 'palakollu', label: 'Palakollu' },
  { value: 'narasannapeta', label: 'Narasannapeta' },
  { value: 'renigunta', label: 'Renigunta' },
  
  // Punjab Cities
  { value: 'ludhiana', label: 'Ludhiana' },
  { value: 'amritsar', label: 'Amritsar' },
  { value: 'jalandhar', label: 'Jalandhar' },
  { value: 'patiala', label: 'Patiala' },
  { value: 'bathinda', label: 'Bathinda' },
  { value: 'mohali', label: 'Mohali' },
  { value: 'firozpur', label: 'Firozpur' },
  { value: 'batala', label: 'Batala' },
  { value: 'pathankot', label: 'Pathankot' },
  { value: 'moga', label: 'Moga' },
  { value: 'abohar', label: 'Abohar' },
  { value: 'malerkotla', label: 'Malerkotla' },
  { value: 'khanna', label: 'Khanna' },
  { value: 'phagwara', label: 'Phagwara' },
  { value: 'muktsar', label: 'Muktsar' },
  { value: 'barnala', label: 'Barnala' },
  { value: 'rajpura', label: 'Rajpura' },
  { value: 'hoshiarpur', label: 'Hoshiarpur' },
  { value: 'kapurthala', label: 'Kapurthala' },
  { value: 'faridkot', label: 'Faridkot' },
  { value: 'sunam', label: 'Sunam' },
  
  // Haryana Cities
  { value: 'chandigarh', label: 'Chandigarh' },
  { value: 'panipat', label: 'Panipat' },
  { value: 'ambala', label: 'Ambala' },
  { value: 'yamunanagar', label: 'Yamunanagar' },
  { value: 'rohtak', label: 'Rohtak' },
  { value: 'hisar', label: 'Hisar' },
  { value: 'karnal', label: 'Karnal' },
  { value: 'sonipat', label: 'Sonipat' },
  { value: 'panchkula', label: 'Panchkula' },
  { value: 'bhiwani', label: 'Bhiwani' },
  { value: 'sirsa', label: 'Sirsa' },
  { value: 'jind', label: 'Jind' },
  { value: 'thanesar', label: 'Thanesar' },
  { value: 'kaithal', label: 'Kaithal' },
  { value: 'rewari', label: 'Rewari' },
  { value: 'narnaul', label: 'Narnaul' },
  { value: 'pundri', label: 'Pundri' },
  { value: 'kosli', label: 'Kosli' },
  { value: 'palwal', label: 'Palwal' },
  
  // Madhya Pradesh Cities
  { value: 'indore', label: 'Indore' },
  { value: 'bhopal', label: 'Bhopal' },
  { value: 'jabalpur', label: 'Jabalpur' },
  { value: 'gwalior', label: 'Gwalior' },
  { value: 'ujjain', label: 'Ujjain' },
  { value: 'sagar', label: 'Sagar' },
  { value: 'dewas', label: 'Dewas' },
  { value: 'satna', label: 'Satna' },
  { value: 'ratlam', label: 'Ratlam' },
  { value: 'rewa', label: 'Rewa' },
  { value: 'singrauli', label: 'Singrauli' },
  { value: 'burhanpur', label: 'Burhanpur' },
  { value: 'khandwa', label: 'Khandwa' },
  { value: 'bhind', label: 'Bhind' },
  { value: 'chhindwara', label: 'Chhindwara' },
  { value: 'guna', label: 'Guna' },
  { value: 'shivpuri', label: 'Shivpuri' },
  { value: 'vidisha', label: 'Vidisha' },
  { value: 'chhatarpur', label: 'Chhatarpur' },
  { value: 'damoh', label: 'Damoh' },
  { value: 'mandsaur', label: 'Mandsaur' },
  { value: 'khargone', label: 'Khargone' },
  { value: 'neemuch', label: 'Neemuch' },
  { value: 'pithampur', label: 'Pithampur' },
  { value: 'narmadapuram', label: 'Narmadapuram' },
  { value: 'itarsi', label: 'Itarsi' },
  { value: 'sehore', label: 'Sehore' },
  { value: 'morena', label: 'Morena' },
  { value: 'betul', label: 'Betul' },
  { value: 'seoni', label: 'Seoni' },
  { value: 'datia', label: 'Datia' },
  { value: 'nagda', label: 'Nagda' },
  { value: 'dhar', label: 'Dhar' },
  
  // Other Major Cities
  { value: 'raipur', label: 'Raipur' },
  { value: 'bhilai', label: 'Bhilai Nagar' },
  { value: 'ranchi', label: 'Ranchi' },
  { value: 'jamshedpur', label: 'Jamshedpur' },
  { value: 'dhanbad', label: 'Dhanbad' },
  { value: 'patna', label: 'Patna' },
  { value: 'gaya', label: 'Gaya' },
  { value: 'bhubaneswar', label: 'Bhubaneswar' },
  { value: 'cuttack', label: 'Cuttack' },
  { value: 'rourkela', label: 'Rourkela' },
  { value: 'guwahati', label: 'Guwahati' },
  { value: 'shimla', label: 'Shimla' },
  { value: 'dehradun', label: 'Dehradun' },
  { value: 'srinagar', label: 'Srinagar' },
  { value: 'jammu', label: 'Jammu' },
  { value: 'panaji', label: 'Panaji' },
  { value: 'puducherry', label: 'Puducherry' },
  { value: 'port-blair', label: 'Port Blair' }
];

// Helper function to get city options for dropdowns
export const getCityOptions = () => {
  return [
    { value: 'all', label: 'All Cities' },
    ...cities
  ];
};

// Helper function to get city label by value
export const getCityLabel = (value) => {
  const city = cities.find(city => city.value === value);
  return city ? city.label : value;
};